#!/usr/bin/env python3
"""
Plot stable core size and related metrics as a function of N or AR.
Reads CSV files generated by analyze_stable_core_vs_n.py
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import argparse
import sys
from pathlib import Path


def plot_stable_core_vs_n(csv_files, output_prefix='stable_core_vs_n', colormap_name='viridis', hue_var='mu', filter_ar=None):
    """
    Generate plots of stable core metrics vs N.
    
    Args:
        csv_files: List of CSV files to plot
        output_prefix: Prefix for output plot files
        colormap_name: Name of the colormap to use
        hue_var: Variable to group by (default: 'mu')
        filter_ar: Specific Aspect Ratio to filter by (optional)
    """
    # Load and combine all data
    dfs = []
    for csv_file in csv_files:
        df = pd.read_csv(csv_file)
        dfs.append(df)
    
    data = pd.concat(dfs, ignore_index=True)
    
    # Filter by AR if requested
    if filter_ar is not None:
        data = data[data['AR'] == float(filter_ar)]
        if data.empty:
            print(f"No data found for AR={filter_ar}")
            return
        print(f"Filtered data for AR={filter_ar}, {len(data)} rows remaining.")

    # Sort by N
    if 'N' in data.columns:
        x_var = 'N'
        x_label = 'Number of Rods (N)'
    elif 'AR' in data.columns:
        x_var = 'AR'
        x_label = 'Aspect Ratio (AR)'
    else:
        print("Error: No N or AR column found in data")
        return
        
    # If x_var and hue_var are the same, disable hue
    if x_var == hue_var:
        hue_var = None

    # Calculate 'tripled' N changes as requested
    if 'n_changes' in data.columns:
        data['n_changes_tripled'] = data['n_changes'] * 3

    # Check for hue column
    has_hue = hue_var in data.columns if hue_var else False
    
    if has_hue:
        # Group by hue_var and x_var
        grouped = data.groupby([hue_var, x_var]).agg({
            'core_size': ['mean', 'std'],
            'core_fraction': ['mean', 'std'],
            'avg_dist': ['mean', 'std'],
            'n_changes_tripled': ['mean', 'std']  # Use the tripled version
        })
        unique_hues = sorted(data[hue_var].unique())
        cmap = plt.get_cmap(colormap_name)
        colors = cmap(np.linspace(0, 1, len(unique_hues)))
    else:
        # Group by x_var only
        grouped = data.groupby(x_var).agg({
            'core_size': ['mean', 'std'],
            'core_fraction': ['mean', 'std'],
            'avg_dist': ['mean', 'std'],
            'n_changes_tripled': ['mean', 'std']
        })
        unique_hues = [None]
        colors = ['blue'] # Default color
    
    # Create figure with subplots
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    
    title_suffix = f" (AR={filter_ar})" if filter_ar is not None else ""

    # Helper function to plot on an axis
    def plot_metric(ax, metric_name, ylabel, title, marker, output_color=None):
        for i, h_val in enumerate(unique_hues):
            if has_hue:
                try:
                    sub_data = grouped.loc[h_val]
                except KeyError:
                    continue 
                label = f'{hue_var}={h_val}'
                color = colors[i]
            else:
                sub_data = grouped
                label = None
                color = output_color if output_color else colors[0]
            
            x_values = sub_data.index.values
            y_mean = sub_data[(metric_name, 'mean')].values
            y_std = sub_data[(metric_name, 'std')].values
            
            ax.errorbar(x_values, y_mean, yerr=y_std, fmt=marker, 
                        linewidth=2, markersize=8, capsize=5, 
                        color=color, label=label)
        
        ax.set_xlabel(x_label, fontsize=12)
        ax.set_ylabel(ylabel, fontsize=12)
        ax.set_title(title + title_suffix, fontsize=14)
        ax.grid(True, alpha=0.3)
        if has_hue:
            ax.legend()
            
    # Plot 1: Stable Core Size
    plot_metric(axes[0, 0], 'core_size', 'Stable Core Size', 
                'Stable Core Size vs ' + x_var, 'o-', output_color='blue' if not has_hue else None)
    
    # Plot 2: Stable Core Fraction
    plot_metric(axes[0, 1], 'core_fraction', 'Stable Core Fraction', 
                'Stable Core Fraction vs ' + x_var, 's-', output_color='green' if not has_hue else None)
    axes[0, 1].set_ylim([0, 1.05])
    
    # Plot 3: Average Distance
    plot_metric(axes[1, 0], 'avg_dist', 'Avg Pairwise Distance', 
                'Average Distance in Stable Core vs ' + x_var, '^-', output_color='red' if not has_hue else None)
    
    # Plot 4: Number of Changes
    plot_metric(axes[1, 1], 'n_changes_tripled', 'Number of Changed Triples', 
                'Topological Changes (Tripled) vs ' + x_var, 'd-', output_color='purple' if not has_hue else None)
    
    plt.tight_layout()
    
    # Save figure
    output_file = f'{output_prefix}.png'
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"Saved plot to {output_file}")
    
    # Print summary statistics
    print("\nSummary Statistics:")
    print("=" * 80)
    print(grouped.to_string())
    print("=" * 80)


def main():
    parser = argparse.ArgumentParser(
        description='Plot stable core metrics vs N or AR'
    )
    parser.add_argument('csv_files', nargs='+', 
                        help='CSV files from analyze_stable_core_vs_n.py')
    parser.add_argument('--output', '-o', default='stable_core_vs_n',
                        help='Output file prefix (default: stable_core_vs_n)')
    parser.add_argument('--colormap', '-c', default='viridis', choices=['jet', 'viridis', 'plasma', 'inferno', 'magma'],
                        help='Colormap to use for overlaying curves (default: viridis)')
    parser.add_argument('--hue', default='mu',
                        help='Variable to group by/overlay (default: mu)')
    parser.add_argument('--filter-ar', type=float,
                        help='Filter data by a specific Aspect Ratio (AR)')
    
    args = parser.parse_args()
    
    plot_stable_core_vs_n(args.csv_files, args.output, args.colormap, args.hue, args.filter_ar)



if __name__ == '__main__':
    main()
