#!/usr/bin/env python3
"""
Plot stable core size and related metrics as a function of N or AR.
Reads CSV files generated by analyze_stable_core_vs_n.py
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import argparse
import sys
from pathlib import Path


def plot_stable_core_vs_n(csv_files, output_prefix='stable_core_vs_n', colormap_name='viridis', hue_var='mu', filter_ar=None, individual_plots=False):
    """
    Generate plots of stable core metrics vs N.
    
    Args:
        csv_files: List of CSV files to plot
        output_prefix: Prefix for output plot files
        colormap_name: Name of the colormap to use
        hue_var: Variable to group by (default: 'mu')
        hue_var: Variable to group by (default: 'mu')
        filter_ar: Specific Aspect Ratio to filter by (optional)
        individual_plots: Whether to generate individual plots for each metric
    """
    # Load and combine all data
    dfs = []
    for csv_file in csv_files:
        df = pd.read_csv(csv_file)
        dfs.append(df)
    
    data = pd.concat(dfs, ignore_index=True)
    
    # Filter by AR if requested
    if filter_ar is not None:
        data = data[data['AR'] == float(filter_ar)]
        if data.empty:
            print(f"No data found for AR={filter_ar}")
            return
        print(f"Filtered data for AR={filter_ar}, {len(data)} rows remaining.")

    # Sort by N
    if 'N' in data.columns:
        x_var = 'N'
        x_label = 'Number of Rods (N)'
    elif 'AR' in data.columns:
        x_var = 'AR'
        x_label = 'Aspect Ratio (AR)'
    else:
        print("Error: No N or AR column found in data")
        return
        
    # If x_var and hue_var are the same, disable hue
    if x_var == hue_var:
        hue_var = None

    # Calculate 'tripled' N changes as requested (Legacy)
    if 'n_changes' in data.columns and 'n_changes_tripled' not in data.columns:
        data['n_changes_tripled'] = data['n_changes'] * 3

    # Determine which metric to plot for the 4th subplot
    if 'fraction_changed' in data.columns:
        change_metric = 'fraction_changed'
        change_label = 'Fraction of Changed Triples'
        change_title = 'Fraction of Changed Triples vs ' + x_var
    else:
        change_metric = 'n_changes_tripled'
        change_label = 'Number of Changed Triples (Tripled)'
        change_title = 'Topological Changes (Tripled) vs ' + x_var

    # Check for hue column
    has_hue = hue_var in data.columns if hue_var else False
    
    # Define aggregation dict
    agg_dict = {
        'core_size': ['mean', 'std'],
        'core_fraction': ['mean', 'std'],
        'avg_dist': ['mean', 'std']
    }
    
    if change_metric in data.columns:
        agg_dict[change_metric] = ['mean', 'std']
    
    # Add linking diff metrics if they exist
    if 'core_linking_diff_norm' in data.columns:
        agg_dict['core_linking_diff_norm'] = ['mean', 'std']
    if 'all_linking_diff_norm' in data.columns:
        agg_dict['all_linking_diff_norm'] = ['mean', 'std']
    
    if has_hue:
        # Group by hue_var and x_var
        grouped = data.groupby([hue_var, x_var]).agg(agg_dict)
        unique_hues = sorted(data[hue_var].unique())
        cmap = plt.get_cmap(colormap_name)
        colors = cmap(np.linspace(0, 1, len(unique_hues)))
    else:
        # Group by x_var only
        grouped = data.groupby(x_var).agg(agg_dict)
        unique_hues = [None]
        colors = ['blue'] # Default color
    
    # Create figure with subplots
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    
    title_suffix = f" (AR={filter_ar})" if filter_ar is not None else ""

    # Helper function to plot on an axis
    def plot_metric(ax, metric_name, ylabel, title, marker, output_color=None):
        if metric_name not in grouped.columns.levels[0]:
            print(f"Warning: {metric_name} not found in grouped data, skipping plot.")
            return

        for i, h_val in enumerate(unique_hues):
            if has_hue:
                try:
                    sub_data = grouped.loc[h_val]
                except KeyError:
                    continue 
                label = f'{hue_var}={h_val}'
                color = colors[i]
            else:
                sub_data = grouped
                label = None
                color = output_color if output_color else colors[0]
            
            x_values = sub_data.index.values
            y_mean = sub_data[(metric_name, 'mean')].values
            y_std = sub_data[(metric_name, 'std')].values
            
            ax.errorbar(x_values, y_mean, yerr=y_std, fmt=marker, 
                        linewidth=2, markersize=8, capsize=5, 
                        color=color, label=label)
        
        ax.set_xlabel(x_label, fontsize=12)
        ax.set_ylabel(ylabel, fontsize=12)
        ax.set_title(title + title_suffix, fontsize=14)
        ax.grid(True, alpha=0.3)
        if has_hue:
            ax.legend()
            
    # Plot 1: Stable Core Size
    plot_metric(axes[0, 0], 'core_size', 'Stable Core Size', 
                'Stable Core Size vs ' + x_var, 'o-', output_color='blue' if not has_hue else None)
    
    # Plot 2: Stable Core Fraction
    plot_metric(axes[0, 1], 'core_fraction', 'Stable Core Fraction', 
                'Stable Core Fraction vs ' + x_var, 's-', output_color='green' if not has_hue else None)
    axes[0, 1].set_ylim([0, 1.05])
    
    # Plot 3: Average Distance
    plot_metric(axes[1, 0], 'avg_dist', 'Avg Pairwise Distance', 
                'Average Distance in Stable Core vs ' + x_var, '^-', output_color='red' if not has_hue else None)
    
    # Plot 4: Number/Fraction of Changes
    plot_metric(axes[1, 1], change_metric, change_label, 
                change_title, 'd-', output_color='purple' if not has_hue else None)
    
    plt.tight_layout()
    
    # Save figure
    output_file = f'{output_prefix}.png'
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"Saved combined plot to {output_file}")
    
    # If individual plots requested, generate them
    if individual_plots:
        print("\nGenerating individual plots...")
        
        # Prepare metrics list with conditional check for existence
        metrics_to_plot = [
            ('core_size', 'Stable Core Size', 'Stable Core Size vs ' + x_var),
            ('core_fraction', 'Stable Core Fraction', 'Stable Core Fraction vs ' + x_var),
            ('avg_dist', 'Avg Pairwise Distance', 'Average Distance in Stable Core vs ' + x_var),
            (change_metric, change_label, change_title)
        ]

        # Add linking diff metrics if they exist
        if 'core_linking_diff_norm' in data.columns:
            metrics_to_plot.append(('core_linking_diff_norm', 'Core Link Diff Norm', 'Stable Core Linking Matrix Diff Norm vs ' + x_var))
        if 'all_linking_diff_norm' in data.columns:
            metrics_to_plot.append(('all_linking_diff_norm', 'All Rods Link Diff Norm', 'All Rods Linking Matrix Diff Norm vs ' + x_var))
        
        # Increase font sizes for small plots
        font_size = 10
        plt.rcParams.update({'font.size': font_size})
        
        for metric, ylabel, title in metrics_to_plot:
            # Create small figure (3x2.5 inches roughly)
            fig_ind, ax_ind = plt.subplots(figsize=(3, 2.5))
            
            # Use helper to plot
            # Note: We can reuse plot_metric logic but need to adapt it since plot_metric assumes 'ax' from subplots
            # Actually, let's just inline the plotting logic or call the inner function if possible.
            # But the inner function 'plot_metric' closes over 'grouped' and 'axes' etc.
            # It's cleaner to re-implement the loop here for the individual ax.
            
            if metric not in grouped.columns.levels[0]:
                continue

            for i, h_val in enumerate(unique_hues):
                if has_hue:
                    try:
                        sub_data = grouped.loc[h_val]
                    except KeyError:
                        continue 
                    label = f'{hue_var}={h_val}'
                    color = colors[i]
                else:
                    sub_data = grouped
                    label = None
                    color = colors[0]
                
                x_values = sub_data.index.values
                y_mean = sub_data[(metric, 'mean')].values
                y_std = sub_data[(metric, 'std')].values
                
                # Determine marker style based on metric
                if metric == 'core_size': marker = 'o-'
                elif metric == 'core_fraction': marker = 's-'
                elif metric == 'avg_dist': marker = '^-'
                else: marker = 'd-'
                
                ax_ind.errorbar(x_values, y_mean, yerr=y_std, fmt=marker, 
                            linewidth=2, markersize=6, capsize=4, 
                            color=color, label=label, alpha=0.8)
            
            ax_ind.set_xlabel(x_label, fontsize=10)
            ax_ind.set_ylabel(ylabel, fontsize=10)
            ax_ind.set_title(title + title_suffix, fontsize=10)
            ax_ind.grid(True, alpha=0.3)
            # Add legend
            if has_hue:
                ax_ind.legend(fontsize=6, loc='best')
            
            # Adjust layout
            plt.tight_layout()
            
            # Save individual plot using the metric name
            ind_output_file_png = f'{output_prefix}_{metric}.png'
            ind_output_file_svg = f'{output_prefix}_{metric}.svg'
            plt.savefig(ind_output_file_png, dpi=300, bbox_inches='tight')
            plt.savefig(ind_output_file_svg, bbox_inches='tight')
            print(f"Saved individual plot: {ind_output_file_png}/.svg")
            plt.close(fig_ind)

    print(f"Saved plot to {output_file}")
    
    # Print summary statistics
    print("\nSummary Statistics:")
    print("=" * 80)
    print(grouped.to_string())
    print("=" * 80)


def main():
    parser = argparse.ArgumentParser(
        description='Plot stable core metrics vs N or AR'
    )
    parser.add_argument('csv_files', nargs='+', 
                        help='CSV files from analyze_stable_core_vs_n.py')
    parser.add_argument('--output', '-o', default='stable_core_vs_n',
                        help='Output file prefix (default: stable_core_vs_n)')
    parser.add_argument('--colormap', '-c', default='viridis', choices=['jet', 'viridis', 'plasma', 'inferno', 'magma'],
                        help='Colormap to use for overlaying curves (default: viridis)')
    parser.add_argument('--hue', default='mu',
                        help='Variable to group by/overlay (default: mu)')
    parser.add_argument('--filter-ar', type=float,
                        help='Filter data by a specific Aspect Ratio (AR)')
    parser.add_argument('--individual-plots', action='store_true',
                        help='Generate individual plots for each metric (PNG and SVG)')
    
    args = parser.parse_args()
    
    plot_stable_core_vs_n(args.csv_files, args.output, args.colormap, args.hue, args.filter_ar, args.individual_plots)



if __name__ == '__main__':
    main()
