#!/usr/bin/env python3
"""
Plot time series data: delta C, average pair distance, and stable core size over time.
Reads CSV files generated by analyze_timeseries.py
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import argparse
import glob
import os


def plot_timeseries_overlay(csv_files, output_file='timeseries_overlay.png'):
    """
    Create overlay plots of multiple time series.
    
    Args:
        csv_files: List of CSV files to plot
        output_file: Output plot file
    """
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    
    colors = plt.cm.tab10(np.linspace(0, 1, len(csv_files)))
    
    for idx, csv_file in enumerate(csv_files):
        df = pd.read_csv(csv_file)
        
        # Extract label from filename
        label = os.path.basename(csv_file).replace('_timeseries.csv', '')
        color = colors[idx]
        
        # Plot 1: Delta C vs time
        axes[0, 0].plot(df['frame'], df['delta_C'], 
                        linewidth=2, label=label, color=color, alpha=0.7)
        
        # Plot 2: Average pair distance vs time
        axes[0, 1].plot(df['frame'], df['avg_pair_distance'], 
                        linewidth=2, label=label, color=color, alpha=0.7)
        
        # Plot 3: Stable core size vs time
        axes[1, 0].plot(df['frame'], df['core_size'], 
                        linewidth=2, label=label, color=color, alpha=0.7)
        
        # Plot 4: Core fraction vs time
        axes[1, 1].plot(df['frame'], df['core_fraction'], 
                        linewidth=2, label=label, color=color, alpha=0.7)
    
    # Configure axes
    axes[0, 0].set_xlabel('Frame', fontsize=12)
    axes[0, 0].set_ylabel(r'$|\Delta C|$', fontsize=12)
    axes[0, 0].set_title('Chirality Change vs Time', fontsize=14)
    axes[0, 0].grid(True, alpha=0.3)
    axes[0, 0].legend(fontsize=8, loc='best')
    
    axes[0, 1].set_xlabel('Frame', fontsize=12)
    axes[0, 1].set_ylabel('Avg Pair Distance', fontsize=12)
    axes[0, 1].set_title('Average Pair Distance vs Time', fontsize=14)
    axes[0, 1].grid(True, alpha=0.3)
    axes[0, 1].legend(fontsize=8, loc='best')
    
    axes[1, 0].set_xlabel('Frame', fontsize=12)
    axes[1, 0].set_ylabel('Stable Core Size', fontsize=12)
    axes[1, 0].set_title('Stable Core Size vs Time', fontsize=14)
    axes[1, 0].grid(True, alpha=0.3)
    axes[1, 0].legend(fontsize=8, loc='best')
    
    axes[1, 1].set_xlabel('Frame', fontsize=12)
    axes[1, 1].set_ylabel('Stable Core Fraction', fontsize=12)
    axes[1, 1].set_title('Stable Core Fraction vs Time', fontsize=14)
    axes[1, 1].grid(True, alpha=0.3)
    axes[1, 1].legend(fontsize=8, loc='best')
    
    plt.tight_layout()
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"Saved overlay plot to {output_file}")


def plot_timeseries_individual(csv_file, output_file=None):
    """
    Create individual time series plot.
    
    Args:
        csv_file: CSV file to plot
        output_file: Output plot file (default: derived from csv_file)
    """
    df = pd.read_csv(csv_file)
    
    if output_file is None:
        output_file = csv_file.replace('.csv', '.png')
    
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    
    # Plot 1: Delta C vs time
    axes[0, 0].plot(df['frame'], df['delta_C'], 'o-', 
                    linewidth=2, markersize=6, color='blue')
    axes[0, 0].set_xlabel('Frame', fontsize=12)
    axes[0, 0].set_ylabel(r'$|\Delta C|$', fontsize=12)
    axes[0, 0].set_title('Chirality Change vs Time', fontsize=14)
    axes[0, 0].grid(True, alpha=0.3)
    
    # Plot 2: Average pair distance vs time
    axes[0, 1].plot(df['frame'], df['avg_pair_distance'], 's-', 
                    linewidth=2, markersize=6, color='green')
    axes[0, 1].set_xlabel('Frame', fontsize=12)
    axes[0, 1].set_ylabel('Avg Pair Distance', fontsize=12)
    axes[0, 1].set_title('Average Pair Distance vs Time', fontsize=14)
    axes[0, 1].grid(True, alpha=0.3)
    
    # Plot 3: Stable core size vs time
    axes[1, 0].plot(df['frame'], df['core_size'], '^-', 
                    linewidth=2, markersize=6, color='red')
    axes[1, 0].set_xlabel('Frame', fontsize=12)
    axes[1, 0].set_ylabel('Stable Core Size', fontsize=12)
    axes[1, 0].set_title('Stable Core Size vs Time', fontsize=14)
    axes[1, 0].grid(True, alpha=0.3)
    
    # Plot 4: Core fraction vs time
    axes[1, 1].plot(df['frame'], df['core_fraction'], 'd-', 
                    linewidth=2, markersize=6, color='purple')
    axes[1, 1].set_xlabel('Frame', fontsize=12)
    axes[1, 1].set_ylabel('Stable Core Fraction', fontsize=12)
    axes[1, 1].set_title('Stable Core Fraction vs Time', fontsize=14)
    axes[1, 1].grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"Saved plot to {output_file}")


def main():
    parser = argparse.ArgumentParser(
        description='Plot time series data from analyze_timeseries.py'
    )
    parser.add_argument('csv_files', nargs='+', 
                        help='CSV files from analyze_timeseries.py')
    parser.add_argument('--output', '-o', default='timeseries_plot.png',
                        help='Output file (default: timeseries_plot.png)')
    parser.add_argument('--overlay', action='store_true',
                        help='Create overlay plot of all files')
    parser.add_argument('--individual', action='store_true',
                        help='Create individual plots for each file')
    
    args = parser.parse_args()
    
    # Expand glob patterns
    csv_files = []
    for pattern in args.csv_files:
        csv_files.extend(glob.glob(pattern))
    
    if not csv_files:
        print("Error: No CSV files found")
        return
    
    print(f"Found {len(csv_files)} CSV files")
    
    if args.overlay or (not args.individual and len(csv_files) > 1):
        plot_timeseries_overlay(csv_files, args.output)
    
    if args.individual or (not args.overlay and len(csv_files) == 1):
        for csv_file in csv_files:
            plot_timeseries_individual(csv_file)


if __name__ == '__main__':
    main()
