#!/usr/bin/env python3
"""
Plot stable core size and related metrics as a function of AR (aspect ratio).
Reads CSV files generated by the AR analysis scripts.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import argparse
import glob
import os


def plot_stable_core_vs_ar(csv_files, output_prefix='stable_core_vs_ar', n_value=None):
    """
    Generate plots of stable core metrics vs AR, with different mu values overlaid.
    
    Args:
        csv_files: List of CSV files to plot
        output_prefix: Prefix for output plot files
        n_value: Optional N value for title
    """
    # Load and combine all data
    dfs = []
    for csv_file in csv_files:
        df = pd.read_csv(csv_file)
        dfs.append(df)
    
    data = pd.concat(dfs, ignore_index=True)
    
    # Check for required columns
    if 'AR' not in data.columns:
        print("Error: No AR column found in data")
        return
    
    # Sort by mu (if present), then AR
    if 'mu' in data.columns:
        data = data.sort_values(['mu', 'AR'])
        has_mu = True
        mu_values = sorted(data['mu'].unique())
        print(f"Found {len(mu_values)} mu values: {mu_values}")
    else:
        data = data.sort_values('AR')
        has_mu = False
        mu_values = [None]
    
    # Create figure with subplots
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    
    title_suffix = f" (N={n_value})" if n_value else ""
    
    # Define colors for different mu values
    colors = plt.cm.viridis(np.linspace(0, 1, len(mu_values)))
    
    # Plot each mu value separately
    for idx, mu in enumerate(mu_values):
        if has_mu:
            mu_data = data[data['mu'] == mu]
            label = f'μ={mu}'
            color = colors[idx]
        else:
            mu_data = data
            label = 'All data'
            color = 'blue'
        
        # Group by AR and compute statistics
        grouped = mu_data.groupby('AR').agg({
            'core_size': ['mean', 'std'],
            'core_fraction': ['mean', 'std'],
            'avg_dist': ['mean', 'std'],
            'n_changes': ['mean', 'std']
        })
        
        ar_values = grouped.index.values
        
        # Plot 1: Stable Core Size vs AR
        ax = axes[0, 0]
        y_mean = grouped[('core_size', 'mean')].values
        y_std = grouped[('core_size', 'std')].values
        
        ax.errorbar(ar_values, y_mean, yerr=y_std, fmt='o-', 
                    linewidth=2, markersize=6, capsize=4, label=label, color=color, alpha=0.8)
        
        # Plot 2: Stable Core Fraction vs AR
        ax = axes[0, 1]
        y_mean = grouped[('core_fraction', 'mean')].values
        y_std = grouped[('core_fraction', 'std')].values
        
        ax.errorbar(ar_values, y_mean, yerr=y_std, fmt='s-', 
                    linewidth=2, markersize=6, capsize=4, label=label, color=color, alpha=0.8)
        
        # Plot 3: Average Distance vs AR
        ax = axes[1, 0]
        y_mean = grouped[('avg_dist', 'mean')].values
        y_std = grouped[('avg_dist', 'std')].values
        
        ax.errorbar(ar_values, y_mean, yerr=y_std, fmt='^-', 
                    linewidth=2, markersize=6, capsize=4, label=label, color=color, alpha=0.8)
        
        # Plot 4: Number of Changed Triples vs AR
        ax = axes[1, 1]
        y_mean = grouped[('n_changes', 'mean')].values
        y_std = grouped[('n_changes', 'std')].values
        
        ax.errorbar(ar_values, y_mean, yerr=y_std, fmt='d-', 
                    linewidth=2, markersize=6, capsize=4, label=label, color=color, alpha=0.8)
    
    # Configure all axes
    axes[0, 0].set_xlabel('Aspect Ratio (AR)', fontsize=12)
    axes[0, 0].set_ylabel('Stable Core Size', fontsize=12)
    axes[0, 0].set_title('Stable Core Size vs AR' + title_suffix, fontsize=14)
    axes[0, 0].set_xscale('log')
    axes[0, 0].grid(True, alpha=0.3)
    axes[0, 0].legend(fontsize=10, loc='best')
    
    axes[0, 1].set_xlabel('Aspect Ratio (AR)', fontsize=12)
    axes[0, 1].set_ylabel('Stable Core Fraction', fontsize=12)
    axes[0, 1].set_title('Stable Core Fraction vs AR' + title_suffix, fontsize=14)
    axes[0, 1].set_xscale('log')
    axes[0, 1].grid(True, alpha=0.3)
    axes[0, 1].set_ylim([0, 1.05])
    axes[0, 1].legend(fontsize=10, loc='best')
    
    axes[1, 0].set_xlabel('Aspect Ratio (AR)', fontsize=12)
    axes[1, 0].set_ylabel('Avg Pairwise Distance', fontsize=12)
    axes[1, 0].set_title('Average Distance in Stable Core vs AR' + title_suffix, fontsize=14)
    axes[1, 0].set_xscale('log')
    axes[1, 0].grid(True, alpha=0.3)
    axes[1, 0].legend(fontsize=10, loc='best')
    
    axes[1, 1].set_xlabel('Aspect Ratio (AR)', fontsize=12)
    axes[1, 1].set_ylabel('Number of Changed Triples', fontsize=12)
    axes[1, 1].set_title('Topological Changes vs AR' + title_suffix, fontsize=14)
    axes[1, 1].set_xscale('log')
    axes[1, 1].grid(True, alpha=0.3)
    axes[1, 1].legend(fontsize=10, loc='best')
    
    plt.tight_layout()
    
    # Save figure
    output_file = f'{output_prefix}.png'
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"Saved plot to {output_file}")
    
    # Print summary statistics grouped by mu
    if has_mu:
        print("\nSummary Statistics by Friction Coefficient:")
        print("=" * 100)
        for mu in mu_values:
            mu_data = data[data['mu'] == mu]
            grouped = mu_data.groupby('AR').agg({
                'core_size': ['mean', 'std'],
                'core_fraction': ['mean', 'std'],
                'avg_dist': ['mean', 'std'],
                'n_changes': ['mean', 'std']
            })
            print(f"\nμ = {mu}:")
            print("-" * 100)
            print(grouped.to_string())
        print("=" * 100)
    else:
        print("\nSummary Statistics:")
        print("=" * 100)
        grouped = data.groupby('AR').agg({
            'core_size': ['mean', 'std'],
            'core_fraction': ['mean', 'std'],
            'avg_dist': ['mean', 'std'],
            'n_changes': ['mean', 'std']
        })
        print(grouped.to_string())
        print("=" * 100)


def main():
    parser = argparse.ArgumentParser(
        description='Plot stable core metrics vs AR'
    )
    parser.add_argument('csv_files', nargs='+', 
                        help='CSV files from AR analysis')
    parser.add_argument('--output', '-o', default='stable_core_vs_ar',
                        help='Output file prefix (default: stable_core_vs_ar)')
    parser.add_argument('--n-value', type=int, default=None,
                        help='N value for plot title')
    
    args = parser.parse_args()
    
    # Expand glob patterns
    csv_files = []
    for pattern in args.csv_files:
        csv_files.extend(glob.glob(pattern))
    
    if not csv_files:
        print("Error: No CSV files found")
        return
    
    plot_stable_core_vs_ar(csv_files, args.output, args.n_value)


if __name__ == '__main__':
    main()
