#!/usr/bin/env python3
"""
Plot stable core size and related metrics as a function of AR (aspect ratio).
Reads CSV files generated by the AR analysis scripts.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import argparse
import glob
import os


def plot_stable_core_vs_ar(csv_files, output_prefix='stable_core_vs_ar', n_value=None, individual_plots=False):
    """
    Generate plots of stable core metrics vs AR, with different mu values overlaid.
    
    Args:
        csv_files: List of CSV files to plot
        output_prefix: Prefix for output plot files
        n_value: Optional N value for title
    """
    # Load and combine all data
    dfs = []
    for csv_file in csv_files:
        df = pd.read_csv(csv_file)
        dfs.append(df)
    
    data = pd.concat(dfs, ignore_index=True)
    
    # Check for required columns
    if 'AR' not in data.columns:
        print("Error: No AR column found in data")
        return
    
    # Sort by mu (if present), then AR
    if 'mu' in data.columns:
        data = data.sort_values(['mu', 'AR'])
        has_mu = True
        mu_values = sorted(data['mu'].unique())
        print(f"Found {len(mu_values)} mu values: {mu_values}")
    else:
        data = data.sort_values('AR')
        has_mu = False
        mu_values = [None]
    
    # Create figure with subplots
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    
    title_suffix = f" (N={n_value})" if n_value else ""
    
    # Define colors for different mu values
    colors = plt.cm.viridis(np.linspace(0, 1, len(mu_values)))
    
    # Plot each mu value separately
    for idx, mu in enumerate(mu_values):
        if has_mu:
            mu_data = data[data['mu'] == mu]
            label = f'μ={mu}'
            color = colors[idx]
        else:
            mu_data = data
            label = 'All data'
            color = 'blue'
        
        if 'fraction_changed' in mu_data.columns:
            change_metric = 'fraction_changed'
        else:
            change_metric = 'n_changes'

        # Group by AR and compute statistics
        agg_dict = {
            'core_size': ['mean', 'std'],
            'core_fraction': ['mean', 'std'],
            'avg_dist': ['mean', 'std'],
            change_metric: ['mean', 'std']
        }
        
        if 'core_linking_diff_norm' in mu_data.columns:
            agg_dict['core_linking_diff_norm'] = ['mean', 'std']
        if 'all_linking_diff_norm' in mu_data.columns:
            agg_dict['all_linking_diff_norm'] = ['mean', 'std']
        
        grouped = mu_data.groupby('AR').agg(agg_dict)
        
        ar_values = grouped.index.values
        
        # Plot 1: Stable Core Size vs AR
        ax = axes[0, 0]
        y_mean = grouped[('core_size', 'mean')].values
        y_std = grouped[('core_size', 'std')].values
        
        ax.errorbar(ar_values, y_mean, yerr=y_std, fmt='o-', 
                    linewidth=2, markersize=6, capsize=4, label=label, color=color, alpha=0.8)
        
        # Plot 2: Stable Core Fraction vs AR
        ax = axes[0, 1]
        y_mean = grouped[('core_fraction', 'mean')].values
        y_std = grouped[('core_fraction', 'std')].values
        
        ax.errorbar(ar_values, y_mean, yerr=y_std, fmt='s-', 
                    linewidth=2, markersize=6, capsize=4, label=label, color=color, alpha=0.8)
        
        # Plot 3: Average Distance vs AR
        ax = axes[1, 0]
        y_mean = grouped[('avg_dist', 'mean')].values
        y_std = grouped[('avg_dist', 'std')].values
        
        ax.errorbar(ar_values, y_mean, yerr=y_std, fmt='^-', 
                    linewidth=2, markersize=6, capsize=4, label=label, color=color, alpha=0.8)
        
        # Determine which metric to plot for the 4th subplot
        if 'fraction_changed' in mu_data.columns:
            change_metric = 'fraction_changed'
            change_label = 'Fraction of Changed Triples'
            change_title = 'Fraction of Changes vs AR' + title_suffix
        else:
            change_metric = 'n_changes'
            change_label = 'Number of Changed Triples'
            change_title = 'Topological Changes vs AR' + title_suffix

        # Plot 4: Number/Fraction of Changed Triples vs AR
        ax = axes[1, 1]
        y_mean = grouped[(change_metric, 'mean')].values
        y_std = grouped[(change_metric, 'std')].values
        
        ax.errorbar(ar_values, y_mean, yerr=y_std, fmt='d-', 
                    linewidth=2, markersize=6, capsize=4, label=label, color=color, alpha=0.8)
    
    # Configure all axes
    axes[0, 0].set_xlabel('Aspect Ratio (AR)', fontsize=12)
    axes[0, 0].set_ylabel('Stable Core Size', fontsize=12)
    axes[0, 0].set_title('Stable Core Size vs AR' + title_suffix, fontsize=14)
    axes[0, 0].set_xscale('log')
    axes[0, 0].grid(True, alpha=0.3)
    axes[0, 0].legend(fontsize=10, loc='best')
    
    axes[0, 1].set_xlabel('Aspect Ratio (AR)', fontsize=12)
    axes[0, 1].set_ylabel('Stable Core Fraction', fontsize=12)
    axes[0, 1].set_title('Stable Core Fraction vs AR' + title_suffix, fontsize=14)
    axes[0, 1].set_xscale('log')
    axes[0, 1].grid(True, alpha=0.3)
    axes[0, 1].set_ylim([0, 1.05])
    axes[0, 1].legend(fontsize=10, loc='best')
    
    axes[1, 0].set_xlabel('Aspect Ratio (AR)', fontsize=12)
    axes[1, 0].set_ylabel('Avg Pairwise Distance', fontsize=12)
    axes[1, 0].set_title('Average Distance in Stable Core vs AR' + title_suffix, fontsize=14)
    axes[1, 0].set_xscale('log')
    axes[1, 0].grid(True, alpha=0.3)
    axes[1, 0].legend(fontsize=10, loc='best')
    
    axes[1, 1].set_xlabel('Aspect Ratio (AR)', fontsize=12)
    axes[1, 1].set_ylabel(change_label, fontsize=12)
    axes[1, 1].set_title(change_title, fontsize=14)
    axes[1, 1].set_xscale('log')
    axes[1, 1].grid(True, alpha=0.3)
    axes[1, 1].legend(fontsize=10, loc='best')
    
    # If individual plots requested, generate them
    if individual_plots:
        print("\nGenerating individual plots...")
        
        # Prepare metrics list with conditional check for existence
        metrics_to_plot = [
            ('core_size', 'Stable Core Size', 'Stable Core Size vs AR'),
            ('core_fraction', 'Stable Core Fraction', 'Stable Core Fraction vs AR'),
            ('avg_dist', 'Avg Pairwise Distance', 'Avg Distance in Stable Core vs AR'),
            (change_metric, change_label, change_title)
        ]

        # Add linking diff metrics if they exist
        if 'core_linking_diff_norm' in data.columns:
            metrics_to_plot.append(('core_linking_diff_norm', 'Core Link Diff Norm', 'Stable Core Linking Matrix Diff Norm vs AR'))
            
        if 'all_linking_diff_norm' in data.columns:
            metrics_to_plot.append(('all_linking_diff_norm', 'All Link Diff Norm', 'All Rods Linking Matrix Diff Norm vs AR'))
        
        # Increase font sizes for small plots
        font_size = 10
        plt.rcParams.update({'font.size': font_size})
        
        for metric, ylabel, title in metrics_to_plot:
            # Create small figure
            fig_ind, ax_ind = plt.subplots(figsize=(3, 2.5))
            
            # Use original plotting logic helper
            y_min, y_max = float('inf'), float('-inf')
            
            for idx, mu in enumerate(mu_values):
                if has_mu:
                    mu_data = data[data['mu'] == mu]
                    label = f'μ={mu}'
                    color = colors[idx]
                else:
                    mu_data = data
                    label = 'All data'
                    color = 'blue'
                
                # Re-grouping needed? already grouped above but iterating mu again is safer for new axes
                # Actually we can just re-aggregate efficiently
                if has_mu:
                     mu_grouped = mu_data.groupby('AR').agg(agg_dict)
                else:
                     mu_grouped = grouped # fallback if no mu
                
                ar_values = mu_grouped.index.values
                y_mean = mu_grouped[(metric, 'mean')].values
                y_std = mu_grouped[(metric, 'std')].values
                
                # Track min/max for lims if needed
                if len(y_mean) > 0:
                   y_min = min(y_min, np.min(y_mean))
                   y_max = max(y_max, np.max(y_mean))

                ax_ind.errorbar(ar_values, y_mean, yerr=y_std, fmt='o-', 
                            linewidth=1.5, markersize=4, capsize=2, label=label, color=color, alpha=0.8)
            
            ax_ind.set_xlabel('AR', fontsize=font_size)
            ax_ind.set_ylabel(ylabel, fontsize=font_size)
            # ax_ind.set_title(title + title_suffix, fontsize=font_size) # Titles often removed for paper panels
            ax_ind.set_xscale('log')
            ax_ind.tick_params(axis='both', which='major', labelsize=font_size-1)
            ax_ind.grid(True, alpha=0.3)
            
            # Add legend with small font size
            ax_ind.legend(fontsize=6, loc='best') 
            
            plt.tight_layout()
            
            # Save individual files
            base_output = output_prefix
             # Check if output_prefix is a directory or file path
            if os.path.isdir(os.path.dirname(output_prefix) or '.'):
                 # It's a path like study/stable_core_analysis/stable_core_vs_ar_N200
                 # We want study/stable_core_analysis/N200/stable_core_vs_ar_N200_core_size.png
                 pass

            # Just append metric name
            ind_output_base = f"{output_prefix}_{metric}"
            plt.savefig(f"{ind_output_base}.png", dpi=300, bbox_inches='tight')
            plt.savefig(f"{ind_output_base}.svg", dpi=300, bbox_inches='tight')
            plt.close(fig_ind)
            print(f"Saved individual plot: {ind_output_base}.png/.svg")


def main():
    parser = argparse.ArgumentParser(
        description='Plot stable core metrics vs AR'
    )
    parser.add_argument('csv_files', nargs='+', 
                        help='CSV files from AR analysis')
    parser.add_argument('--output', '-o', default='stable_core_vs_ar',
                        help='Output file prefix (default: stable_core_vs_ar)')
    parser.add_argument('--n-value', type=int, default=None,
                        help='N value for plot title')
    parser.add_argument('--individual-plots', action='store_true',
                        help='Generate individual small plots (3x2.5 in) for paper')
    
    args = parser.parse_args()
    
    # Expand glob patterns
    csv_files = []
    for pattern in args.csv_files:
        csv_files.extend(glob.glob(pattern))
    
    if not csv_files:
        print("Error: No CSV files found")
        return
    
    plot_stable_core_vs_ar(csv_files, args.output, args.n_value, args.individual_plots)


if __name__ == '__main__':
    main()
