#!/usr/bin/env python3
"""
analyze_rigidification_sweep.py

Analyzes a batch of runs generated by submit_rigidification_sweep.py.
Generates overlaid plots of key metrics vs time, colored by fSigma.
Also generates individual plots for each run.
"""

import sys
import os
import csv
import re
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

def load_output_csv(path: Path):
    data = {
        "frame": [],
        "contacts": [],
        "KE": [],
        "max_overlap": [],
        "gyration_sq": [],
        "reldisp_sq": [],
        "ent_sum": [],
        "ent_pairs": []
    }

    if not path.exists():
        print(f"Warning: {path} does not exist.")
        return None

    with path.open(newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            data["frame"].append(int(row["frame"]))
            data["contacts"].append(float(row["contacts"]))
            data["KE"].append(float(row["KE"]))
            data["max_overlap"].append(float(row["max_overlap"]))
            
            # Handle variations in column names if any
            if "gyration_sq" in row:
                data["gyration_sq"].append(float(row["gyration_sq"]))
            elif "reldisp_norm" in row:
                data["gyration_sq"].append(float(row["reldisp_norm"]))
            else:
                data["gyration_sq"].append(0.0)

            if "reldisp_sq" in row:
                data["reldisp_sq"].append(float(row["reldisp_sq"]))
            else:
                data["reldisp_sq"].append(0.0)
                
            if "ent_sum" in row:
                data["ent_sum"].append(float(row["ent_sum"]))
            else:
                data["ent_sum"].append(0.0)
                
            if "ent_pairs" in row:
                data["ent_pairs"].append(float(row["ent_pairs"]))
            else:
                data["ent_pairs"].append(0.0)

    return data

def plot_individual_run(run_dir: Path, data):
    """Generates a summary plot for a single run."""
    if not data:
        return

    x = data["frame"]
    reldisp_norm = [val**0.5 for val in data["reldisp_sq"]]

    fig, axes = plt.subplots(6, 1, figsize=(10, 15), sharex=True)

    axes[0].plot(x, data["contacts"])
    axes[0].set_ylabel("Contacts")
    axes[0].set_title(f"Run: {run_dir.name}")
    axes[0].set_yscale('log')

    axes[1].plot(x, data["KE"])
    axes[1].set_ylabel("Kinetic Energy")
    axes[1].set_yscale('log')

    axes[2].plot(x, data["max_overlap"])
    axes[2].set_ylabel("Max Overlap")
    axes[2].set_yscale('log')

    axes[3].plot(x, data["gyration_sq"])
    axes[3].set_ylabel("Gyration Sq")
    axes[3].set_yscale('log')

    axes[4].plot(x, reldisp_norm)
    axes[4].set_ylabel("Rel Disp Norm")
    axes[4].set_yscale('log')
    
    axes[5].plot(x, data["ent_sum"])
    axes[5].set_ylabel("Entanglement Sum")
    axes[5].set_xlabel("Frame")
    axes[5].set_yscale('log')

    fig.tight_layout()
    plt.savefig(run_dir / "summary_plot.png")
    plt.close(fig)
    print(f"Generated summary plot for {run_dir.name}")

def extract_fsigma(dirname):
    """Extracts fSigma value from directory name."""
    # Expected format: ..._fSig1.0e-06
    match = re.search(r"fSig([\d\.e\+\-]+)", dirname)
    if match:
        return float(match.group(1))
    return None

def extract_ar(dirname):
    """Extracts Aspect Ratio (AR) from directory name."""
    # Expected format: ...-AR0100-... or ...ar30...
    match = re.search(r"[aA][rR](\d+)", dirname)
    if match:
        return float(match.group(1))
    return None

def extract_density(dirname):
    """Extracts Density from directory name."""
    # Expected format: ..._dens0.3_... or ..._dens10_...
    match = re.search(r"dens([\d\.]+)", dirname)
    if match:
        return float(match.group(1))
    return None

def main():
    if len(sys.argv) < 2:
        print("Usage: python analyze_rigidification_sweep.py <batch_dir1> [batch_dir2 ...]")
        sys.exit(1)

    batch_dirs = [Path(d) for d in sys.argv[1:]]
    for d in batch_dirs:
        if not d.is_dir():
            print(f"Error: {d} is not a directory.")
            sys.exit(1)

    # Use the first directory for output
    output_dir = batch_dirs[0]
    print(f"Outputting plots to: {output_dir}")

    raw_runs = []

    # 1. Collect all runs from all directories
    for b_dir in batch_dirs:
        print(f"Scanning batch: {b_dir}")
        for run_dir in sorted(b_dir.iterdir()):
            if not run_dir.is_dir():
                continue
            
            output_csv = run_dir / "output.csv"
            if not output_csv.exists():
                continue

            f_sigma = extract_fsigma(run_dir.name)
            ar_val = extract_ar(run_dir.name)
            density = extract_density(run_dir.name)
            
            if f_sigma is None: f_sigma = 0.0
            if ar_val is None: ar_val = 0.0
            if density is None: density = 0.0

            print(f"  Loading {run_dir.name} (AR={ar_val}, Dens={density}, fSigma={f_sigma})...")
            data = load_output_csv(output_csv)
            
            if data:
                # Generate individual run summary
                plot_individual_run(run_dir, data) 
                
                # Compute final stats for this single run
                n_avg = 10
                final_stats = {}
                for key in ["KE", "contacts", "max_overlap", "gyration_sq", "reldisp_sq", "ent_sum"]:
                    if len(data[key]) > 0:
                        vals = data[key][-n_avg:] if len(data[key]) >= n_avg else data[key]
                        final_stats[key] = np.mean(vals)
                    else:
                        final_stats[key] = 0.0

                raw_runs.append({
                    "f_sigma": f_sigma,
                    "ar": ar_val,
                    "density": density,
                    "data": data,
                    "final_stats": final_stats,
                    "name": run_dir.name,
                    "source_batch": b_dir.name
                })

    if not raw_runs:
        print("No valid run data found.")
        sys.exit(0)

    # 2. Aggregate data by (AR, Density, fSigma)
    grouped = {}
    for r in raw_runs:
        key = (r["ar"], r["density"], r["f_sigma"])
        if key not in grouped:
            grouped[key] = []
        grouped[key].append(r)
    
    print(f"Found {len(grouped)} unique parameter combinations (AR, Density, fSigma). Aggregating...")
    
    runs_data = [] 
    
    for (ar, dens, f_sigma), group in grouped.items():
        # Aggregate Time Series
        min_len = min(len(g["data"]["frame"]) for g in group)
        
        ts_keys = ["KE", "contacts", "max_overlap", "gyration_sq", "reldisp_sq", "ent_sum"]
        
        agg_data = {"frame": group[0]["data"]["frame"][:min_len]} 
        agg_stats = {} 
        
        for k in ts_keys:
            arrays = [g["data"][k][:min_len] for g in group]
            arr = np.array(arrays)
            agg_data[k] = np.mean(arr, axis=0)
            agg_data[f"{k}_std"] = np.std(arr, axis=0)
            
        for k in ts_keys:
            vals = [g["final_stats"][k] for g in group]
            agg_stats[k] = np.mean(vals)
            agg_stats[f"{k}_std"] = np.std(vals)
        
        runs_data.append({
            "ar": ar,
            "density": dens,
            "f_sigma": f_sigma,
            "data": agg_data,
            "final_stats": agg_stats,
            "count": len(group)
        })
        
    runs_data.sort(key=lambda x: (x["ar"], x["density"]))
    batch_dir = output_dir

    unique_f_sigmas = sorted(list(set(r["f_sigma"] for r in runs_data)))
    unique_ars = sorted(list(set(r["ar"] for r in runs_data)))
    unique_densities = sorted(list(set(r["density"] for r in runs_data)))

    metrics = [
        ("KE", "Kinetic Energy"),
        ("max_overlap", "Max Overlap"),
        ("reldisp_sq", "Relative Displacement Squared"),
        ("ent_sum", "Entanglement Sum"),
        ("gyration_sq", "Gyration Squared")
    ]

    print(f"Generating overlaid time plots. fSigma={len(unique_f_sigmas)}, AR={len(unique_ars)}, Dens={len(unique_densities)}")

    # Plot Type A: color by Density (Fixed fSigma, Fixed AR)
    if len(unique_densities) > 1:
        cmap = plt.get_cmap("viridis")
        norm = plt.Normalize(vmin=min(unique_densities), vmax=max(unique_densities))
        if min(unique_densities) > 0 and max(unique_densities)/min(unique_densities) > 100:
             from matplotlib.colors import LogNorm
             norm = LogNorm(vmin=min(unique_densities), vmax=max(unique_densities))

        for f_val in unique_f_sigmas:
            for ar_val in unique_ars:
                subset = [r for r in runs_data if r["f_sigma"] == f_val and r["ar"] == ar_val]
                subset.sort(key=lambda x: x["density"])
                
                if len(subset) < 2: continue 

                for metric_key, metric_label in metrics:
                    fig, ax = plt.subplots(figsize=(10, 6))
                    for run in subset:
                        dens = run["density"]
                        color = cmap(norm(dens))
                        ax.plot(run["data"]["frame"], run["data"][metric_key], 
                                label=f"Dens={dens:.4g}", color=color, alpha=0.9)

                    ax.set_xlabel("Frame")
                    ax.set_ylabel(metric_label)
                    ax.set_title(f"{metric_label} vs Time (fSig={f_val:.1e}, AR={ar_val})")
                    ax.set_yscale('log')
                    ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left', title="Density")
                    ax.grid(True, alpha=0.3, which="both")
                    plt.tight_layout()
                    
                    savename = f"overlaid_{metric_key}_vs_time_by_dens_fSig{f_val:.1e}_AR{ar_val}.png"
                    plt.savefig(batch_dir / savename)
                    plt.close(fig)
        
    # Plot Type B: color by AR (Fixed fSigma, Fixed Density) 
    if len(unique_ars) > 1:
        cmap = plt.get_cmap("viridis")
        norm = plt.Normalize(vmin=min(unique_ars), vmax=max(unique_ars))
        if max(unique_ars)/min(unique_ars) > 50:
             from matplotlib.colors import LogNorm
             norm = LogNorm(vmin=min(unique_ars), vmax=max(unique_ars))

        for f_val in unique_f_sigmas:
            for dens_val in unique_densities:
                subset = [r for r in runs_data if r["f_sigma"] == f_val and r["density"] == dens_val]
                subset.sort(key=lambda x: x["ar"])
                
                if len(subset) < 2: continue
                
                for metric_key, metric_label in metrics:
                    fig, ax = plt.subplots(figsize=(10, 6))
                    for run in subset:
                        ar = run["ar"]
                        color = cmap(norm(ar))
                        ax.plot(run["data"]["frame"], run["data"][metric_key], 
                                label=f"AR={ar}", color=color, alpha=0.9)

                    ax.set_xlabel("Frame")
                    ax.set_ylabel(metric_label)
                    ax.set_title(f"{metric_label} vs Time (fSig={f_val:.1e}, Dens={dens_val})")
                    ax.set_yscale('log')
                    ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left', title="Aspect Ratio")
                    ax.grid(True, alpha=0.3, which="both")
                    plt.tight_layout()
                    
                    savename = f"overlaid_{metric_key}_vs_time_by_AR_fSig{f_val:.1e}_Dens{dens_val}.png"
                    plt.savefig(batch_dir / savename)
                    plt.close(fig)

    print("Saved overlaid time plots.")

    # 4. Metric vs Density 
    if len(unique_densities) > 1:
        print("Generating Metric vs Density plots...")
        d_norm = plt.Normalize(vmin=min(unique_densities), vmax=max(unique_densities))
        
        for metric_key, metric_label in metrics:
            fig, ax = plt.subplots(figsize=(8, 6))
            
            for ar_val in unique_ars:
                for f_val in unique_f_sigmas:
                    subset = [r for r in runs_data if r["ar"] == ar_val and r["f_sigma"] == f_val]
                    subset.sort(key=lambda x: x["density"])
                    
                    if len(subset) < 2: continue
                    
                    ds = [r["density"] for r in subset]
                    y_vals = [r["final_stats"][metric_key] for r in subset]
                    y_errs = [r["final_stats"][f"{metric_key}_std"] for r in subset]
                    
                    label = f"fSig={f_val:.1e} (AR={ar_val})"
                    ax.errorbar(ds, y_vals, yerr=y_errs, fmt='o-', label=label, markersize=6, capsize=3)
            
            ax.set_xlabel("Density (Normalized)")
            ax.set_ylabel(f"Final {metric_label}")
            ax.set_title(f"Final {metric_label} vs Density")
            ax.set_xscale('log')
            ax.set_yscale('log')
            ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
            ax.grid(True, which="both", alpha=0.4)
            
            plt.tight_layout()
            plt.savefig(batch_dir / f"metric_vs_Density_{metric_key}.png")
            plt.close(fig)

    # 5. Metric vs fSigma
    if len(unique_f_sigmas) > 1:
        print("Generating Metric vs fSigma plots...")
        
        for metric_key, metric_label in metrics:
            fig, ax = plt.subplots(figsize=(8, 6))
            
            for ar_val in unique_ars:
                # For each density?
                for dens in unique_densities:
                    subset = [r for r in runs_data if r["ar"] == ar_val and r["density"] == dens]
                    subset.sort(key=lambda x: x["f_sigma"])
                    
                    if len(subset) < 2: continue
                    
                    fs = [r["f_sigma"] for r in subset]
                    y_vals = [r["final_stats"][metric_key] for r in subset]
                    y_errs = [r["final_stats"][f"{metric_key}_std"] for r in subset]
                    
                    label = f"Dens={dens} (AR={ar_val})"
                    ax.errorbar(fs, y_vals, yerr=y_errs, fmt='o-', label=label, markersize=6, capsize=3)
            
            ax.set_xlabel("fSigma")
            ax.set_ylabel(f"Final {metric_label}")
            ax.set_title(f"Final {metric_label} vs fSigma")
            ax.set_xscale('log')
            ax.set_yscale('log')
            ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
            ax.grid(True, which="both", alpha=0.4)
            
            plt.tight_layout()
            plt.savefig(batch_dir / f"metric_vs_fSigma_{metric_key}.png")
            plt.close(fig)

    print("Analysis complete.")

if __name__ == "__main__":
    main()
