#!/usr/bin/env python3
"""analyze_entangled_n200.py

Analyze time-evolution metrics for entangled N200 batch runs.

Expected per-run outputs (generated by rigidbody_viewer_3d):
  - output.csv with columns:
      frame,contacts,KE,max_overlap,gyration_sq,reldisp_sq,ent_sum,ent_pairs

This script:
  - scans a batch directory for run subfolders containing output.csv
  - parses AR and seed-folder from run folder name (e.g. *_199_97_131_AR100)
  - writes per-run timeseries plots
  - writes overlaid-by-AR plots using mean +/- std over seeds
  - writes a summary CSV

Example:
  python parametric_study/analyze_entangled_n200.py \
    /n/holylabs/LABS/mahadevan_lab/Users/yjung/rod-dynamics-3d/runs/Dec20_Entangled_N200

"""



import argparse
import csv
import math
import re

from pathlib import Path
from typing import Dict, List, Optional, Tuple

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


RUN_RE = re.compile(r"_([0-9]+_[0-9]+_[0-9]+)_AR(\d+)")


SCALES = ("linear", "semilogy", "loglog")


class RunData:
    def __init__(self, run_dir: Path, run_name: str, seed: str, ar: int, n_rods: int, friction: float, frame: np.ndarray, ke: np.ndarray, contacts: np.ndarray, max_overlap: np.ndarray, gyration_sq: np.ndarray, reldisp_sq: np.ndarray, ent_sum: np.ndarray, ent_pairs: np.ndarray, rms_contact_distance: Optional[np.ndarray] = None, max_cluster_fraction: Optional[np.ndarray] = None):
        self.run_dir = run_dir
        self.run_name = run_name
        self.seed = seed
        self.ar = ar
        self.n_rods = n_rods
        self.friction = friction
        self.frame = frame
        self.ke = ke
        self.contacts = contacts
        self.max_overlap = max_overlap
        self.gyration_sq = gyration_sq
        self.reldisp_sq = reldisp_sq
        self.ent_sum = ent_sum
        self.ent_pairs = ent_pairs
        self.rms_contact_distance = rms_contact_distance
        self.max_cluster_fraction = max_cluster_fraction


import json

def get_run_n(run_dir: Path) -> int:
    """Try to determine N (rod count) from scene.json or fallback."""
    try:
        scene_path = run_dir / "scene.json"
        if scene_path.exists():
            data = json.loads(scene_path.read_text())
            # Look for populate.count or bodies list length
            if "scene" in data:
                sc = data["scene"]
                if "populate" in sc and "count" in sc["populate"]:
                    return int(sc["populate"]["count"])
                if "bodies" in sc and isinstance(sc["bodies"], list):
                    return len(sc["bodies"])
    except Exception:
        pass
    # Fallback default if not found
    return 200

def get_run_friction(run_dir: Path) -> float:
    """Try to determine friction from scene.json or fallback."""
    try:
        scene_path = run_dir / "scene.json"
        if scene_path.exists():
            data = json.loads(scene_path.read_text())
            # Look for physics.soft_contact.mu
            if "physics" in data and "soft_contact" in data["physics"]:
                return float(data["physics"]["soft_contact"].get("mu", 0.4))
    except Exception:
        pass
    return 0.4


def load_network_metrics(path: Path, n_rods: int, force: bool = False, burst_gap: int = 50) -> Tuple[Optional[Dict[int, float]], Optional[Dict[int, int]]]:
    """Stream network.csv and compute:
      1. Per-frame RMS of contact distance (instantaneous).
      2. Aggegrated max connected component size (accumulated over bursts).

    Wraps computation with JSON caching.
    Cache file: <run_dir>/network_metrics.json
    """
    run_dir = path.parent
    cache_path = run_dir / "network_metrics.json"

    # Try loading cache
    if not force and cache_path.exists():
        try:
            data = json.loads(cache_path.read_text())
            # Check if cached burst_gap matches (optional validation, or just trust user)
            # For simplicity, if cache exists we use it unless force is set. 
            # If user changes burst_gap, they should use --force.
            
            rms_out = {int(k): v for k, v in data.get("rms_out", {}).items()}
            cluster_out = {int(k): v for k, v in data.get("cluster_out", {}).items()}
            return (rms_out if rms_out else None), (cluster_out if cluster_out else None)
        except Exception:
            pass

    if not path.exists():
        return None, None

    # 1. Read all data first (memory usage should be fine for typical N200/N1331 runs)
    # Store: frame -> list of (u, v, dist)
    frames_data: Dict[int, List[Tuple[int, int, float]]] = {}
    
    with path.open(newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            return None, None
        
        has_dist = "distance" in reader.fieldnames
        
        for row in reader:
            try:
                fr = int(float(row.get("frame", "0")))
                ri = int(float(row.get("rod_i", "-1")))
                rj = int(float(row.get("rod_j", "-1")))
                if ri < 0 or rj < 0:
                    continue
                
                d = float(row.get("distance", "0")) if has_dist else 0.0
                if has_dist and not math.isfinite(d):
                    continue

                frames_data.setdefault(fr, []).append((ri, rj, d))
            except Exception:
                continue

    if not frames_data:
        return None, None

    rms_out: Dict[int, float] = {}
    cluster_out: Dict[int, int] = {}

    # Sort frames to identify bursts
    sorted_frames = sorted(frames_data.keys())
    
    # 2. Compute RMS contact distance (Instantaneous)
    for fr in sorted_frames:
        dists = [d for (_, _, d) in frames_data[fr]]
        if dists:
            rms_out[fr] = math.sqrt(sum(x*x for x in dists) / len(dists))
        else:
            rms_out[fr] = float("nan")

    # Group frames into bursts
    bursts: List[List[int]] = []
    current_burst: List[int] = [sorted_frames[0]]
    
    for i in range(1, len(sorted_frames)):
        fr = sorted_frames[i]
        prev = sorted_frames[i-1]
        if fr - prev > burst_gap:
            bursts.append(current_burst)
            current_burst = [fr]
        else:
            current_burst.append(fr)
    bursts.append(current_burst)

    # Union-Find Helper
    class UnionFind:
        def __init__(self, n):
            self.parent = list(range(n))
        
        def find(self, i):
            path = []
            while self.parent[i] != i:
                path.append(i)
                i = self.parent[i]
            for p in path:
                self.parent[p] = i
            return i
        
        def union(self, i, j):
            root_i = self.find(i)
            root_j = self.find(j)
            if root_i != root_j:
                self.parent[root_i] = root_j
        
        def max_component_size(self):
            counts = {}
            for i in range(len(self.parent)):
                r = self.find(i)
                counts[r] = counts.get(r, 0) + 1
            return max(counts.values()) if counts else 1

    # Process each burst
    for burst_frames in bursts:
        uf = UnionFind(n_rods)
        
        # Accumulate edges from ALL frames in this burst
        for fr in burst_frames:
            contacts = frames_data[fr]
            if has_dist and contacts:
                sum_sq = sum(c[2]*c[2] for c in contacts)
                rms_out[fr] = math.sqrt(sum_sq / len(contacts))
            
            for u, v, _ in contacts:
                 if u < n_rods and v < n_rods:
                     uf.union(u, v)
        
        max_size = uf.max_component_size()
        for fr in burst_frames:
            cluster_out[fr] = max_size

    # Save to cache
    try:
        cache_data = {
            "rms_out": rms_out,
            "cluster_out": cluster_out
        }
        cache_path.write_text(json.dumps(cache_data))
    except Exception as e:
        print(f"Warning: Failed to write cache {cache_path}: {e}")

    return (rms_out if has_dist else None), cluster_out


def parse_run_id(run_name: str) -> Optional[Tuple[str, int]]:
    """Return (seed, ar) from run folder name."""
    m = RUN_RE.search(run_name)
    if not m:
        return None
    return (m.group(1), int(m.group(2)))


def load_output_csv(path: Path) -> Optional[Dict[str, np.ndarray]]:
    if not path.exists():
        return None

    cols = {
        "frame": [],
        "contacts": [],
        "KE": [],
        "max_overlap": [],
        "gyration_sq": [],
        "reldisp_sq": [],
        "ent_sum": [],
        "ent_pairs": [],
    }

    with path.open(newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            return None

        for row in reader:
            try:
                cols["frame"].append(int(row.get("frame", "0")))
                cols["contacts"].append(float(row.get("contacts", "0")))
                cols["KE"].append(float(row.get("KE", "0")))
                cols["max_overlap"].append(float(row.get("max_overlap", "0")))
                cols["gyration_sq"].append(float(row.get("gyration_sq", "0")))
                cols["reldisp_sq"].append(float(row.get("reldisp_sq", "0")))
                cols["ent_sum"].append(float(row.get("ent_sum", "0")))
                cols["ent_pairs"].append(float(row.get("ent_pairs", "0")))
            except Exception:
                # skip malformed row
                continue

    if len(cols["frame"]) == 0:
        return None

    return {k: np.asarray(v) for k, v in cols.items()}


def _positive_floor(y: np.ndarray) -> float:
    finite_pos = y[np.isfinite(y) & (y > 0)]
    if finite_pos.size == 0:
        return 1e-12
    return float(np.nanmin(finite_pos))


def apply_scale(ax: plt.Axes, scale: str) -> None:
    if scale == "linear":
        ax.set_xscale("linear")
        ax.set_yscale("linear")
    elif scale == "semilogy":
        ax.set_xscale("linear")
        ax.set_yscale("log")
    elif scale == "loglog":
        ax.set_xscale("log")
        ax.set_yscale("log")
    else:
        raise ValueError(f"Unknown scale: {scale}")


def safe_mean_std_band(mean: np.ndarray, std: np.ndarray, floor: float):
    lower = mean - std
    upper = mean + std
    lower = np.where(np.isfinite(lower), np.maximum(lower, floor), np.nan)
    upper = np.where(np.isfinite(upper), np.maximum(upper, floor), np.nan)
    return lower, upper


def plot_run_timeseries(run: RunData, out_dir: Path, scale: str, dt: float, xlabel: str = "Time (s)") -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    # Time axis
    t = run.frame * dt
    # For log-x plots, avoid t=0 problem (if desired, or just mask it)
    x = t
    if scale == "loglog":
        x = np.where(t == 0, t[1] if len(t) > 1 else 1e-6, t)

    rms_gyr = np.sqrt(np.maximum(run.gyration_sq, 0.0))
    rms_reldisp = np.sqrt(np.maximum(run.reldisp_sq, 0.0))
    
    # Normalized entanglement
    ent_norm = np.full_like(run.ent_sum, np.nan)
    valid_pairs = run.ent_pairs > 0
    ent_norm[valid_pairs] = run.ent_sum[valid_pairs] / run.ent_pairs[valid_pairs]

    have_net = run.rms_contact_distance is not None
    have_clust = run.max_cluster_fraction is not None
    
    # Determine number of rows
    # Base: KE, EntSum, EntNorm, RelDisp, Gyration (5)
    # Optional: RMS Contact (1), Cluster (1)
    
    base_rows = 5
    extra_rows = (1 if have_net else 0) + (1 if have_clust else 0)
    nrows = base_rows + extra_rows
    
    fig, axes = plt.subplots(nrows, 1, figsize=(10, 3*nrows), sharex=True)
    if nrows == 1: axes = [axes] # robust check

    idx = 0
    axes[idx].plot(x, run.ke)
    axes[idx].set_ylabel("KE")
    idx += 1

    axes[idx].plot(x, run.ent_sum)
    axes[idx].set_ylabel("Entanglement sum")
    idx += 1

    axes[idx].plot(x, ent_norm)
    axes[idx].set_ylabel("Norm Ent (sum/pairs)")
    idx += 1

    axes[idx].plot(x, rms_reldisp)
    axes[idx].set_ylabel("RMS rel. disp")
    idx += 1

    axes[idx].plot(x, rms_gyr)
    axes[idx].set_ylabel("RMS gyration")
    idx += 1

    if have_net:
        axes[idx].plot(x, run.rms_contact_distance)
        axes[idx].set_ylabel("RMS contact dist")
        idx += 1
        
    if have_clust:
        axes[idx].plot(x, run.max_cluster_fraction)
        axes[idx].set_ylabel("Max Cluster Frac")
        idx += 1

    axes[nrows-1].set_xlabel(xlabel)

    for ax in axes:
        apply_scale(ax, scale)
        ax.grid(True, alpha=0.25, which="both")

    title = f"{run.run_name} (seed={run.seed}, AR={run.ar}) [{scale}]"
    fig.suptitle(title)
    fig.tight_layout(rect=[0, 0, 1, 0.97])
    fig.savefig(out_dir / f"timeseries_{run.run_name}_{scale}.png", dpi=160)
    plt.close(fig)

def plot_overlaid_by_ar(runs: List[RunData], out_dir: Path, scale: str, dt: float, xlabel: str = "Time (s)") -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    # Group by AR
    by_ar: Dict[int, List[RunData]] = {}
    for r in runs:
        by_ar.setdefault(r.ar, []).append(r)

    def get_ent_norm(r: RunData):
        val = np.full_like(r.ent_sum, np.nan)
        msk = r.ent_pairs > 0
        val[msk] = r.ent_sum[msk] / r.ent_pairs[msk]
        return val

    metrics = [
        ("KE", lambda r: r.ke, "KE"),
        ("ent_sum", lambda r: r.ent_sum, "Entanglement sum"),
        ("ent_norm", get_ent_norm, "Norm Ent (sum/pairs)"),
        ("rms_reldisp", lambda r: np.sqrt(np.maximum(r.reldisp_sq, 0.0)), "RMS rel. disp"),
        ("rms_gyration", lambda r: np.sqrt(np.maximum(r.gyration_sq, 0.0)), "RMS gyration"),
    ]

    # Optional network-based metric (only if at least one run has it)
    if any(r.rms_contact_distance is not None for r in runs):
        metrics.append(
            (
                "rms_contact_distance",
                lambda r: (r.rms_contact_distance if r.rms_contact_distance is not None else np.full_like(r.frame, np.nan, dtype=float)),
                "RMS contact distance",
            )
        )
    if any(r.max_cluster_fraction is not None for r in runs):
        metrics.append(
            (
                "max_cluster_fraction",
                lambda r: (r.max_cluster_fraction if r.max_cluster_fraction is not None else np.full_like(r.frame, np.nan, dtype=float)),
                "Max Cluster Fraction (size/N)",
            )
        )

    for key, get_series, ylabel in metrics:
        fig, ax = plt.subplots(figsize=(10, 6))

        for ar in sorted(by_ar.keys()):
            group = by_ar[ar]
            # Align by truncating to min length
            min_len = min(len(r.frame) for r in group)
            if min_len < 2:
                continue

            x0 = group[0].frame[:min_len] * dt
            # If log, mask 0
            x = x0
            if scale == "loglog":
                 x = np.where(x0 == 0, x0[1] if len(x0) > 1 else 1e-6, x0)

            Y = np.vstack([get_series(r)[:min_len] for r in group])
            mean = np.nanmean(Y, axis=0)
            std = np.nanstd(Y, axis=0)

            if scale in ("semilogy", "loglog"):
                floor = _positive_floor(mean)
                mean_plot = np.where(np.isfinite(mean), np.maximum(mean, floor), np.nan)
                ax.plot(x, mean_plot, label=f"AR={ar} (n={len(group)})")
                lower, upper = safe_mean_std_band(mean, std, floor)
                ax.fill_between(x, lower, upper, alpha=0.15)
            else:
                ax.plot(x, mean, label=f"AR={ar} (n={len(group)})")
                ax.fill_between(x, mean - std, mean + std, alpha=0.15)

        ax.set_xlabel(xlabel)
        ax.set_ylabel(ylabel)
        ax.set_title(f"{ylabel} vs time (mean±std over seeds) [{scale}]")
        ax.grid(True, alpha=0.3, which="both")
        ax.legend(bbox_to_anchor=(1.02, 1), loc="upper left")

        apply_scale(ax, scale)

        fig.tight_layout()
        fig.savefig(out_dir / f"overlaid_by_ar_{key}_{scale}.png", dpi=160)
        plt.close(fig)


def plot_metrics_vs_ar(runs: List[RunData], out_dir: Path) -> None:
    """Plot final values of metrics vs Aspect Ratio, grouped by Friction."""
    out_dir.mkdir(parents=True, exist_ok=True)
    
    # Nested dict: Friction -> AR -> Metric -> List of values
    data_map: Dict[float, Dict[int, Dict[str, List[float]]]] = {}
    
    for r in runs:
        if r.frame.size == 0:
            continue
            
        # Calculate final values
        ent_norm_val = np.nan
        if r.ent_pairs[-1] > 0:
            ent_norm_val = r.ent_sum[-1] / r.ent_pairs[-1]
            
        cluster_val = np.nan
        if r.max_cluster_fraction is not None and r.max_cluster_fraction.size > 0:
            cluster_val = r.max_cluster_fraction[-1]
            
        metrics = {
            "ent_norm": ent_norm_val,
            "ent_sum": r.ent_sum[-1],
            "max_cluster_fraction": cluster_val,
            "rms_gyration": np.sqrt(max(r.gyration_sq[-1], 0.0)),
            "contacts": r.contacts[-1],
        }
        
        fric_entry = data_map.setdefault(r.friction, {})
        ar_entry = fric_entry.setdefault(r.ar, {})
        
        for k, v in metrics.items():
            ar_entry.setdefault(k, []).append(v)

    # Plot each metric
    metric_labels = {
        "ent_norm": "Final Norm. Entanglement",
        "ent_sum": "Final Entanglement Sum",
        "max_cluster_fraction": "Final Max Cluster Fraction",
        "rms_gyration": "Final RMS Gyration",
        "contacts": "Final Contacts",
    }
    
    # We want to iterate metrics, then plot lines for each friction
    all_frictions = sorted(data_map.keys())
    
    for metric_key, label in metric_labels.items():
        # Check if any data exists
        has_data = False
        fig, ax = plt.subplots(figsize=(8, 6))
        
        for fric in all_frictions:
            ar_map = data_map[fric]
            sorted_ars = sorted(ar_map.keys())
            
            X, Y, Yerr = [], [], []
            for ar in sorted_ars:
                vals = ar_map[ar].get(metric_key, [])
                vals = [v for v in vals if np.isfinite(v)]
                if not vals:
                    continue
                
                X.append(ar)
                Y.append(np.mean(vals))
                Yerr.append(np.std(vals))
            
            if X:
                has_data = True
                ax.errorbar(X, Y, yerr=Yerr, fmt='o-', capsize=5, label=f"Mu={fric}")

        if not has_data:
            plt.close(fig)
            continue
            
        ax.set_xlabel("Aspect Ratio (AR)")
        ax.set_ylabel(label)
        ax.set_title(f"{label} vs AR")
        ax.grid(True, alpha=0.3)
        ax.legend()
        
        # Log scale x-axis if range large
        valid_x = [ar for fric in data_map for ar in data_map[fric]]
        if valid_x and max(valid_x) / (min(valid_x)+1e-9) > 10:
             ax.set_xscale("log")
             
        fig.tight_layout()
        fig.savefig(out_dir / f"final_{metric_key}_vs_ar.png", dpi=160)
        plt.close(fig)


def plot_metrics_vs_friction(runs: List[RunData], out_dir: Path) -> None:
    """Plot final values of metrics vs Friction Coefficient, grouped by AR."""
    out_dir.mkdir(parents=True, exist_ok=True)
    
    # Nested dict: AR -> Friction -> List of final values
    # We want to plot one line per AR. X-axis is Friction.
    
    # 1. Collect data
    data_map: Dict[int, Dict[float, Dict[str, List[float]]]] = {}
    
    for r in runs:
        if r.frame.size == 0:
            continue
            
        ar_map = data_map.setdefault(r.ar, {})
        fric_map = ar_map.setdefault(r.friction, {})
        
        # Metrics
        ent_norm_val = np.nan
        if r.ent_pairs[-1] > 0:
            ent_norm_val = r.ent_sum[-1] / r.ent_pairs[-1]
            
        cluster_val = np.nan
        if r.max_cluster_fraction is not None and r.max_cluster_fraction.size > 0:
            cluster_val = r.max_cluster_fraction[-1]
        
        # Add to lists
        fric_map.setdefault("ent_norm", []).append(ent_norm_val)
        fric_map.setdefault("ent_sum", []).append(r.ent_sum[-1])
        fric_map.setdefault("max_cluster_fraction", []).append(cluster_val)
        fric_map.setdefault("rms_gyration", []).append(math.sqrt(max(r.gyration_sq[-1], 0.0)))
        fric_map.setdefault("contacts", []).append(r.contacts[-1])

    # 2. Plotting
    # We iterate over metrics
    metric_labels = {
        "ent_norm": "Final Norm. Entanglement",
        "ent_sum": "Final Entanglement Sum",
        "max_cluster_fraction": "Final Max Cluster Fraction",
        "rms_gyration": "Final RMS Gyration",
        "contacts": "Final Contacts",
    }
    
    # Find all unique ARs
    all_ars = sorted(data_map.keys())
    
    for metric_key, label in metric_labels.items():
        # Check if we have valid data anywhere
        has_data = False
        
        fig, ax = plt.subplots(figsize=(8, 6))
        
        for ar in all_ars:
            # Prepare X (friction) and Y (mean metric)
            fric_map = data_map[ar]
            sorted_frics = sorted(fric_map.keys())
            
            X, Y, Yerr = [], [], []
            for f in sorted_frics:
                vals = fric_map[f].get(metric_key, [])
                vals = [v for v in vals if np.isfinite(v)]
                if vals:
                    X.append(f)
                    Y.append(np.mean(vals))
                    Yerr.append(np.std(vals))
            
            if X:
                has_data = True
                ax.errorbar(X, Y, yerr=Yerr, fmt='o-', capsize=5, label=f"AR={ar}")

        if not has_data:
            plt.close(fig)
            continue
            
        ax.set_xlabel(r"Friction Coefficient ($\mu$)")
        ax.set_ylabel(label)
        ax.set_title(f"{label} vs Friction")
        ax.grid(True, alpha=0.3)
        ax.legend()
        
        fig.tight_layout()
        fig.savefig(out_dir / f"final_{metric_key}_vs_friction.png", dpi=160)
        plt.close(fig)


def main() -> None:
    ap = argparse.ArgumentParser(description="Analyze entangled N200 batch runs.")
    ap.add_argument("batch_dir", type=Path, help="Batch directory containing run subfolders")
    ap.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output directory (default: <batch_dir>/analysis)",
    )
    ap.add_argument(
        "--per-run",
        action="store_true",
        help="Generate per-run timeseries PNGs",
    )
    ap.add_argument(
        "--scales",
        type=str,
        default="linear,semilogy,loglog",
        help="Comma-separated plot scales: linear, semilogy, loglog",
    )
    ap.add_argument(
        "--use-network",
        action="store_true",
        help="If network.csv exists, compute RMS contact distance per frame.",
    )
    ap.add_argument(
        "--dt",
        type=float,
        default=0.0005,
        help="Timestep size for x-axis scaling (default: 0.0005)",
    )
    ap.add_argument(
        "--force",
        action="store_true",
        help="Force re-computation of network metrics (ignoring cache).",
    )
    ap.add_argument(
        "--timescale",
        type=float,
        default=None,
        help="Optional timescale t_c. If provided, creates extra plots vs t/t_c.",
    )
    ap.add_argument(
        "--burst-gap",
        type=int,
        default=50,
        help="Max gap between frames to consider them part of the same logging burst (default: 50).",
    )
    args = ap.parse_args()

    scales = [s.strip() for s in args.scales.split(",") if s.strip()]
    for s in scales:
        if s not in SCALES:
            raise SystemExit(f"Unknown scale '{s}'. Use: {', '.join(SCALES)}")

    batch_dir = args.batch_dir
    if not batch_dir.is_dir():
        raise SystemExit(f"Not a directory: {batch_dir}")

    out_dir = args.out if args.out is not None else (batch_dir / "analysis")
    out_dir.mkdir(parents=True, exist_ok=True)

    runs: List[RunData] = []
    for run_dir in sorted(batch_dir.iterdir()):
        if not run_dir.is_dir():
            continue
        rid = parse_run_id(run_dir.name)
        if rid is None:
            continue

        seed, ar = rid
        n_rods = get_run_n(run_dir)
        friction = get_run_friction(run_dir)
        
        out_csv = run_dir / "output.csv"
        data = load_output_csv(out_csv)
        if data is None:
            continue

        rms_contact_dist_series: Optional[np.ndarray] = None
        max_cluster_series: Optional[np.ndarray] = None
        
        if args.use_network:
            net_path = run_dir / "network.csv"
            # load_network_metrics returns (rms_map, cluster_map)
            rms_map, cluster_map = load_network_metrics(net_path, n_rods, force=args.force, burst_gap=args.burst_gap)
            
            if rms_map is not None:
                rms_contact_dist_series = np.asarray(
                    [rms_map.get(int(fr), float("nan")) for fr in data["frame"]],
                    dtype=float,
                )
            
            if cluster_map is not None:
                max_cluster_series = np.asarray(
                    [cluster_map.get(int(fr), 0) / float(n_rods) for fr in data["frame"]],
                    dtype=float,
                )

        runs.append(
            RunData(
                run_dir=run_dir,
                run_name=run_dir.name,
                seed=seed,
                ar=ar,
                n_rods=n_rods,
                friction=friction,
                frame=data["frame"],
                ke=data["KE"],
                contacts=data["contacts"],
                max_overlap=data["max_overlap"],
                gyration_sq=data["gyration_sq"],
                reldisp_sq=data["reldisp_sq"],
                ent_sum=data["ent_sum"],
                ent_pairs=data["ent_pairs"],
                rms_contact_distance=rms_contact_dist_series,
                max_cluster_fraction=max_cluster_series,
            )
        )

    if not runs:
        raise SystemExit("No runs found with output.csv and parsable name.")

    # Write summary CSV
    summary_path = out_dir / "summary.csv"
    with summary_path.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(
            [
                "run",
                "seed",
                "AR",
                "N",
                "friction",
                "frames",
                "time_end",
                "KE0",
                "KE_end",
                "ent_sum_end",
                "ent_norm_end",
                "rms_reldisp_end",
                "rms_gyr_end",
                "rms_contact_distance_end",
                "max_cluster_frac_end",
            ]
        )
        for r in runs:
            rms_reldisp = math.sqrt(max(float(r.reldisp_sq[-1]), 0.0))
            rms_gyr = math.sqrt(max(float(r.gyration_sq[-1]), 0.0))
            pairs_end = float(r.ent_pairs[-1])
            ent_sum_end = float(r.ent_sum[-1])
            ent_norm_end = ent_sum_end / pairs_end if pairs_end > 0 else float("nan")
            
            rms_contact_end = (
                float(r.rms_contact_distance[-1])
                if r.rms_contact_distance is not None and r.rms_contact_distance.size > 0
                else float("nan")
            )
            
            cluster_frac_end = (
                float(r.max_cluster_fraction[-1])
                if r.max_cluster_fraction is not None and r.max_cluster_fraction.size > 0
                else float("nan")
            )
            
            w.writerow(
                [
                    r.run_name,
                    r.seed,
                    r.ar,
                    r.n_rods,
                    r.friction,
                    int(r.frame.size),
                    float(r.frame[-1]) * args.dt,
                    float(r.ke[0]),
                    float(r.ke[-1]),
                    ent_sum_end,
                    ent_norm_end,
                    rms_reldisp,
                    rms_gyr,
                    rms_contact_end,
                    cluster_frac_end,
                ]
            )

    # Plots
    # Generate vs-AR summary plots
    plot_metrics_vs_ar(runs, out_dir)
    # Generate vs-Friction summary plots
    plot_metrics_vs_friction(runs, out_dir)

    # Standard Plots (Time in seconds)
    print("Generating standard time plots...")
    for scale in scales:
        scale_dir = out_dir / scale
        plot_overlaid_by_ar(runs, scale_dir, scale=scale, dt=args.dt, xlabel="Time (s)")

        if args.per_run:
            per_run_dir = scale_dir / "per_run"
            for r in runs:
                plot_run_timeseries(r, per_run_dir, scale=scale, dt=args.dt, xlabel="Time (s)")

    # Nondimensional Plots (t/t_c)
    if args.timescale is not None:
        print(f"Generating nondimensional plots (timescale={args.timescale})...")
        dt_nondim = args.dt / args.timescale
        xlabel_nondim = r"Time ($\tilde{t} = t/t_c$)"
        
        for scale in scales:
            # Create distinct directories for nondim plots, e.g. "loglog_nondim"
            scale_dir_nd = out_dir / f"{scale}_nondim"
            
            plot_overlaid_by_ar(runs, scale_dir_nd, scale=scale, dt=dt_nondim, xlabel=xlabel_nondim)

            if args.per_run:
                per_run_dir_nd = scale_dir_nd / "per_run"
                for r in runs:
                    plot_run_timeseries(r, per_run_dir_nd, scale=scale, dt=dt_nondim, xlabel=xlabel_nondim)

    print(f"Loaded {len(runs)} runs")
    print(f"Wrote: {summary_path}")
    print(f"Wrote plots under: {out_dir}")


if __name__ == "__main__":
    main()
